# Generated by Django 2.1.1 on 2018-10-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20181019_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
